---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  volumes:
    - name: task-pv-volume
      persistentVolumeClaim:
        claimName: task-pv-claim
    - name: kaniko-secret
      secret:
        secretName: docker-secret
        items:
          - key: .dockerconfigjson
            path: config.json
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: IfNotPresent
      args: ["--dockerfile=./<dockerfile>",
             "--context=dir:///data",
             "--destination=<destination>",
             "--verbosity=info"]
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-volume
        - name: kaniko-secret
          mountPath: /kaniko/.docker

  restartPolicy: Never
